require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   # skip("Add a hash of attributes valid for your model")
  #   attributes_for(:user)
  # }

  let(:invalid_attributes) {
    { name: 'Invalid User', email: 'invalid@domain' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all users as @users" do
      user = User.create! attributes_for(:user)
      get :index, {}, valid_session
      expect(assigns(:users)).to eq([user])
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "assigns the requested user as @user" do
      user = User.create! attributes_for(:user)
      get :show, {:id => user.id}, valid_session
      expect(assigns(:user)).to eq(user)
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => attributes_for(:user)}, valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:user => attributes_for(:user)}, valid_session
        expect(assigns(:user)).to be_a(User)
        expect(assigns(:user)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        invalid_user = attributes_for(:user)
        invalid_user = invalid_user.merge invalid_attributes
        post :create, {:user => invalid_user}, valid_session
        # expect(assigns(:user)).to be_a_new(User)
        # expect(assigns(:user)).to be_persisted
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: Faker::Name.name}
      }

      it "updates the requested user" do
        user = User.create! attributes_for(:user)
        put :update, {:id => user.id, :user => new_attributes}, valid_session
        user.reload
        expect(user.name).to eq(new_attributes[:name])
      end

      it "assigns the requested user as @user" do
        user = User.create! attributes_for(:user)
        put :update, {:id => user.id, :user => attributes_for(:user)}, valid_session
        expect(assigns(:user)).to eq(user)
      end
    end

    context "with invalid params" do
      it "assigns the user as @user" do
        user = User.create! attributes_for(:user)
        put :update, {:id => user.id, :user => invalid_attributes}, valid_session
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do
      user = User.create! attributes_for(:user)
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end
  end

end
