require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::UsersController, type: :controller do

  let(:admin){
    FactoryGirl.create(:user, :admin)
  }

  let(:user){
    FactoryGirl.create(:user)
  }

  let(:admin_auth) {
    ActionController::HttpAuthentication::Basic.encode_credentials(admin.email, admin.password)
  }

  let(:user_auth){
    ActionController::HttpAuthentication::Basic.encode_credentials(user.email, user.password)
  }
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:user_attributes) {
    attributes_for(:user)
  }

  let(:invalid_attributes) {
    { name: 'Invalid User', email: 'invalid@domain' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  # let(:valid_session) {
  #   # TODO: Can't use this as a valid_session, so will fill the request
  #   {'HTTP_AUTHORIZATION' => admin_auth }
  # }

  describe "GET #index" do
    it "assigns all users as @users" do
      user = User.create! user_attributes
      get :index, {}
      expect(assigns(:users)).to include(user)
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "assigns the requested user as @user" do
      user = User.create! user_attributes
      get :show, {:id => user.id}
      expect(assigns(:user)).to eq(user)
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "as administrator" do
      context "with valid params" do
        it "creates a new User" do
          expect {
            request.env['HTTP_AUTHORIZATION'] = admin_auth
            post :create, {:user => user_attributes}
          }.to change(User.user, :count).by(1)
        end

        it "assigns a newly created user as @user" do
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          post :create, {:user => user_attributes}
          expect(assigns(:user)).to be_a(User)
          expect(assigns(:user)).to be_persisted
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved user as @user" do
          invalid_user = user_attributes.merge invalid_attributes
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          post :create, {:user => invalid_user}
          expect(response).to have_http_status(422)
        end
      end
    end
  end

  describe "PUT #update" do
    context "as administrator" do
      context "with valid params" do
        let(:new_attributes) {
          {name: Faker::Name.name}
        }

        it "updates the requested user" do
          user = User.create! user_attributes
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          put :update, {:id => user.id, :user => new_attributes}
          user.reload
          expect(user.name).to eq(new_attributes[:name])
        end

        it "assigns the requested user as @user" do
          user = User.create! user_attributes
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          put :update, {:id => user.id, :user => user_attributes}
          expect(assigns(:user)).to eq(user)
        end
      end

      context "with invalid params" do
        it "assigns the user as @user" do
          user = User.create! attributes_for(:user)
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          put :update, {:id => user.id, :user => invalid_attributes}
          expect(response).to have_http_status(422)
        end
      end
    end

    describe "DELETE #destroy" do
      context "as administrator" do
        it "destroys the requested user" do
          user = User.create! user_attributes
          request.env['HTTP_AUTHORIZATION'] = admin_auth
          expect {
            delete :destroy, {:id => user.to_param}
          }.to change(User.user, :count).by(-1)
        end
      end
    end
  end

end
